server:
  port: 8083

spring:
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5432/webfluxdb
    username: postgres
    password: 12314
  flyway:
    url: jdbc:postgresql://localhost:5432/webfluxdb
    locations: classpath:db/migration
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}

jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      keylength: 256
